### ISSUE TITLE
[BUG] “Azure IoT Explorer (preview)” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by parso** [Azure/azure-iot-explorer#435]
**Describe the bug**
Mac OS will not run the app because Azure IoT Explorer (preview)” can’t be opened because Apple cannot check it for malicious software.

**To Reproduce**
download latest dmg file to your mac
once installed try to open the application
the attached screen shot is displayed

**Expected behavior**
Message box asking if it is ok to run app

**Screenshots**
See attached

**Desktop (please complete the following information):**
 - OS: OSX
 - Version 11.2.3
 - App version Azure.IoT.Explorer.preview.-0.14.1.dmg and Azure.IoT.Explorer.preview.-0.14.0.dmg

**Comment by YingXue** [comment]
Hi @parso,
In order to enable running without malicious check on Mac, we have to publish the app through Apple's store, which is not in our scope.
To bypass the check, please override the security settings: https://support.apple.com/guide/mac-help/apple-cant-check-app-for-malicious-software-mchleab3a043/mac
